### ISSUE TITLE
Return option causes app crash

### ISSUE THREAD

**Issue by vladimir-puzic** [vladimir-puzic/pos_software#29]
Table Management
1 - List Tables
2 - Create Tables
0 - Return - <class 'menu_screens.MenuDatabaseManagement'>
0
Traceback (most recent call last):
  File "e:\PROJECTS\pos_software\main.py", line 39, in <module>
    s.s_option.execute()
  File "e:\PROJECTS\pos_software\menu_screens.py", line 66, in execute
    session.menu = self._menu()
    ^^^^^^^
NameError: name 'session' is not defined

App crashes when return option is selected.

**Comment by vladimir-puzic** [comment]
Changed line 41 in **menu_screens.py**
from: **session.menu = self._menu()**
to: **s.s_menu = self._menu()**

This resolved the initial error

**Comment by vladimir-puzic** [comment]
New error present:

Database Management 
1 - Table Management
0 - Return - <class 'menu_screens.MainMenu'>
0
Traceback (most recent call last):
  File "e:\PROJECTS\pos_software\main.py", line 39, in <module>
    s.s_option.execute()
  File "e:\PROJECTS\pos_software\menu_screens.py", line 66, in execute
    s.s_menu = self._menu()
               ^^^^^^^^^^^^
TypeError: MainMenu.__init__() missing 1 required positional argument: 'db_name'

**Comment by vladimir-puzic** [comment]
Issue resolved in commit f22e871

Issue was caused by a varying number of arguments expected by the Menu Classes and Menu Item Classes, and also their respective **execute** functions.

This was resolved by adding **'*args'** argument allowing the classes and functions to accept a varying amount of arguments.
